"""Rename readings table to analyses

Revision ID: 4b7da55652ea
Revises: 8e67a8651264
Create Date: 2025-09-03 19:57:49.653304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7da55652ea'
down_revision = '6c0fcf67d508'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('readings', 'analyses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('analyses', 'readings')
    # ### end Alembic commands ###