"""add conversation enhancements

Revision ID: 510a5ec8160b
Revises: d06f421a11ca
Create Date: 2025-09-08 14:47:06.874777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510a5ec8160b'
down_revision = 'd06f421a11ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add enums first
    conversation_mode_enum = sa.Enum('ANALYSIS', 'CHAT', name='conversationmode')
    conversation_mode_enum.create(op.get_bind(), checkfirst=True)
    
    message_type_enum = sa.Enum('INITIAL_READING', 'USER_QUESTION', 'AI_RESPONSE', name='messagetype')
    message_type_enum.create(op.get_bind(), checkfirst=True)
    
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', conversation_mode_enum, nullable=False, server_default='CHAT'))
        batch_op.add_column(sa.Column('has_initial_message', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.create_index(batch_op.f('ix_conversations_mode'), ['mode'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', message_type_enum, nullable=False, server_default='USER_QUESTION'))
        batch_op.add_column(sa.Column('analysis_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_messages_message_type'), ['message_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_message_type'))
        batch_op.drop_column('analysis_data')
        batch_op.drop_column('message_type')

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_mode'))
        batch_op.drop_column('has_initial_message')
        batch_op.drop_column('mode')

    # ### end Alembic commands ###