"""add_key_features_strengths_guidance_to_analyses

Revision ID: 5e48529687fb
Revises: 8e67a8651264
Create Date: 2025-09-04 14:37:12.217515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e48529687fb'
down_revision = '8e67a8651264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('key_features', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('guidance', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'guidance')
    op.drop_column('analyses', 'strengths')
    op.drop_column('analyses', 'key_features')
    # ### end Alembic commands ###