"""migrate_to_responses_api_add_file_ids_remove_thread_id

Revision ID: 7ad583db3e3f
Revises: 5e48529687fb
Create Date: 2025-09-04 15:41:41.151424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ad583db3e3f'
down_revision = '5e48529687fb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('left_file_id', sa.String(255), nullable=True))
    op.add_column('analyses', sa.Column('right_file_id', sa.String(255), nullable=True))
    op.drop_column('analyses', 'thread_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('thread_id', sa.String(255), nullable=True))
    op.drop_column('analyses', 'right_file_id')
    op.drop_column('analyses', 'left_file_id')
    # ### end Alembic commands ###