"""Add thread_id field to analyses table

Revision ID: 8e67a8651264
Revises: 6c0fcf67d508
Create Date: 2025-09-03 19:51:15.476648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e67a8651264'
down_revision = '4b7da55652ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('thread_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'thread_id')
    # ### end Alembic commands ###